data = [
    {'fname': 'Cori',
     'lname': 'Lint',
     'cello_details': '2014 Y. Chen, Cleveland',
     'bio': 'Cori Lint is a cellist-turned-software engineer from Cleveland, Ohio. After earning a degree in cello performance from the University of Michigan, Cori joined a cruise ship to perform with string quartet Thalia Strings, and when back on land, pivoted into orchestra and festival production. She is a founder of Classical Revolution St. Pete, and a member of Artists Who Code, an online community advocating for creative professionals in the tech industry.',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615509731/seed_cellist_photos/IMG_4767_ue3hcf.jpg',
     'music_url': 'https://www.youtube.com/watch?v=_yiQJmvaxZc&list=PLq64-yDZbigJzoa2WXemZM-0Abc74oK-n',
     'teacher_ids': [2, 3]
     },
    {'fname': 'Anthony',
     'lname': 'Elliott',
     'cello_details': '1703 David Tecchler, Rome. A wedding gift to the Duke of Edinburgh in 1874. See more: https://ur.umich.edu/0203/Aug11_03/10.shtml',
     'bio': 'Cellist Anthony Elliott is in great demand as a soloist, chamber music performer, and teacher. Following his victory in the Emanuel Feuermann International Cello Competition in 1987, Strad Magazine wrote of his competition appearance, “his emotional communication is often profound, and his glittering, silvery tone captivates the ear.” Following quickly on the heels of his competition victory was a highly successful New York debut recital, which received a lengthy standing ovation from a capacity crowd.',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615508895/seed_cellist_photos/anthony_elliott_xhlbug.jpg',
     'music_url': 'http://www.anthonyelliott.net/',
     'teacher_ids': [6, 8]
     },
    {'fname': 'Martha',
     'lname': 'Baldwin',
     'cello_details': 'Eugene Holtier, North Ridgeville, Ohio',
     'bio': 'Since 2001, Martha has been a member of the cello section of The Cleveland Orchestra.  As a performer she has appeared extensively in solo and chamber music performances across the globe and has been broadcast on NPR and CBC radio nationally. A passionate and dedicated teacher, Martha has taught at The Cleveland Institute of Music for more than a decade and served as Chair of the Preparatory String department for 5 years. She has given classes and seminars across the U.S. and Canada and regularly serves on competition juries in the U.S. and Canada.  Martha’s students have graduated from nearly every major conservatory and university music school in the U.S. and are frequent winners of numerous competitions. \n \n A native of Calgary, Alberta, Martha is a graduate of Rice University’s Shepherd School of Music and The Cleveland Institute of Music and has studied with such renowned pedagogues as John Kadz, Harvey Shapiro, Paul Katz, Desmond Hoebig, Aldo Parisot, and Stephen Geber.  Martha is an active teaching artist and leader in The Cleveland Orchestra’s Education Department where she works on everything from concert scripts to strategic planning. Martha lives in the Cleveland area with her husband, daughter, and dog and plays on a cello made by Eugene Holtier of North Ridgeville, Ohio.',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615508897/seed_cellist_photos/martha_baldwin_eg3o7h.jpg',
     'music_url': 'https://theplannedpractice.com/',
     'teacher_ids': [5, 15]
     },
    {'fname': 'Melissa',
     'lname': 'Kraut',
     'cello_details': '',
     'bio': 'Co-head of the cello department at the Cleveland Institute of Music, Dr. Melissa Kraut is recognized as one of the leading pedagogues of her generation. Having developed and trained some of the outstanding young musicians of today, Dr. Kraut has demonstrated a unique ability to teach all ages and stages of dedicated students, helping them reach their highest potential both at and away from the cello. With degrees from the Cleveland Institute of Music, the University of Iowa and Northwestern University, Dr. Kraut has had the opportunity to study with the great pedagogues Alan Harris and Hans-Jorgen Jensen as well as summer study/master classes with cellists such as Aldo Parisot, Frank Miller, Yo-Yo Ma, Tsuyoshi Tsutsumi and David Soyer. As a student, she participated in the Aspen Music Festival, Banff Center for the Arts and the Schleswig-Holstein Music Festival in Europe. An active performer, Dr. Kraut has led a diverse career on stage, with solo and chamber performances throughout the United States and Europe. She has held leadership positions in several orchestras, and has played under the baton of conductors such as Sir Georg Solti, Valery Gergiev and Semyon Bychkov. Dr. Kraut currently enjoys performing chamber music with her friends and colleagues throughout the world. ',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615508896/seed_cellist_photos/i_KrautMelissa_rect-1-1_i3sbbi.jpg',
     'music_url': 'https://www.melissakraut.com',
     'teacher_ids': [5]
     },
    {'fname': 'Hans',
     'lname': 'Jørgen Jensen',
     'cello_details': '',
     'bio': '',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615508896/seed_cellist_photos/hjj_rggidu.jpg',
     'music_url': '',
     'teacher_ids': [11, 10]
     },
    {'fname': 'János',
     'lname': 'Starker',
     'cello_details': '',
     'bio': '',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615508899/seed_cellist_photos/starker_btsj25.jpg',
     'music_url': 'https://open.spotify.com/artist/6D7itIGHznFfHx3ZDqCk3j',
     'teacher_ids': [36]
     },
    {'fname': 'Brant',
     'lname': 'Taylor',
     'cello_details': '',
     'bio': '',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615508895/seed_cellist_photos/brant_taylor_tccqgw.jpg',
     'music_url': '',
     'teacher_ids': [6]
     },
    {'fname': 'Frank',
     'lname': 'Miller',
     'cello_details': '',
     'bio': '',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615508895/seed_cellist_photos/082-frank-miller-1959_l4skxj.jpg',
     'music_url': '',
     'teacher_ids': [37]
     },
    {'fname': 'Erica',
     'lname': 'Snowden-Rodriguez',
     'cello_details': '',
     'bio': '',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615508896/seed_cellist_photos/ericasr_whvlyy.jpg',
     'music_url': '',
     'teacher_ids': [4]
     },
    {'fname': 'Leonard',
     'lname': 'Rose',
     'cello_details': '',
     'bio': '',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615508901/seed_cellist_photos/Rose-5_id6dhh.jpg',
     'music_url': '',
     'teacher_ids': []
     },
    {'fname': 'Pierre',
     'lname': 'Fournier',
     'cello_details': '',
     'bio': '',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615508896/seed_cellist_photos/fournier_mtbi8v.jpg',
     'music_url': '',
     'teacher_ids': []
     },
    {'fname': 'Tina',
     'lname': 'Guo',
     'cello_details': 'Tina performs on her Gand & Bernardel Cello made in Paris, France, in 1880. On electric cello, she plays a customized Yamaha SVC-210.  Tina also plays an Erhu made in Shanghai, China and Native American Flutes made in the Navajo Nation.',
     'bio': 'Internationally acclaimed, GRAMMY Award-nominated and BRIT Female Artist of the Year-nominated musician Tina Guo has established an international career as a virtuoso acoustic/electric cellist, multi-instrumentalist, composer, and entrepreneur. Known for her unique genre-crossing style, she is one of the most recorded Solo Cellists of all time and can be heard on hundreds of Blockbuster Film, Television, and Game Soundtracks.  Tina is currently recording for four feature film soundtracks remotely from her home studio during the coronavirus pandemic, including DUNE (2021) and Top Gun: Maverick (2021).  She has just completed her upcoming 2020 winter album WINTER NIGHT: TRACES IN THE SNOW and 2021 solo album DIES IRAE released on Sony Masterworks. ',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615508899/seed_cellist_photos/tinaguo2_sviclj.jpg',
     'music_url': 'https://tinaguo.com/music',
     'teacher_ids': [13, 38]
     },
    {'fname': 'Nathaniel',
     'lname': 'Rosen',
     'cello_details': '',
     'bio': '',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615508898/seed_cellist_photos/rosen_ha4bf4.jpg',
     'music_url': '',
     'teacher_ids': []
     },
    {'fname': 'Gregor',
     'lname': 'Piatagorsky',
     'cello_details': '',
     'bio': '',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615508902/seed_cellist_photos/piatagorsky2_belouf.jpg',
     'music_url': '',
     'teacher_ids': []
     },
    {'fname': 'Stephen',
     'lname': 'Geber',
     'cello_details': '',
     'bio': '',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615508896/seed_cellist_photos/geber_wdxfsq.jpg',
     'music_url': '',
     'teacher_ids': [35, 48]
     },
    {'fname': 'Sheku',
     'lname': 'Kanneh-Mason',
     'cello_details': '',
     'bio': '',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615508899/seed_cellist_photos/sheku_fviorc.jpg',
     'music_url': '',
     'teacher_ids': [17]
     },
    {'fname': 'Hannah',
     'lname': 'Roberts',
     'cello_details': '',
     'bio': '',
     'img_url': '',
     'music_url': '',
     'teacher_ids': [18]
     },
    {'fname': 'Ralph',
     'lname': 'Kirshbaum',
     'cello_details': 'Montagnana also played by Piatti',
     'bio': '',
     'img_url': '',
     'music_url': '',
     'teacher_ids': [20, 19, 14]
     },
    {'fname': 'Aldo',
     'lname': 'Parisot',
     'cello_details': '',
     'bio': '',
     'img_url': '',
     'music_url': '',
     'teacher_ids': []
     },
    {'fname': 'Lev',
     'lname': 'Aronson',
     'cello_details': '',
     'bio': '',
     'img_url': 'https://patronmagazine.com/wp-content/uploads/2017/06/Aronson-pointing.jpg',
     'music_url': '',
     'teacher_ids': [14]
     },
    {'fname': 'Rushad',
     'lname': 'Eggleston',
     'cello_details': '',
     'bio': '',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615508898/seed_cellist_photos/rushad_nxeikh.jpg',
     'music_url': '',
     'teacher_ids': [22]
     },
    {'fname': 'Eugene',
     'lname': 'Friesen',
     'cello_details': '',
     'bio': '',
     'img_url': '',
     'music_url': '',
     'teacher_ids': [14]
     },
    {'fname': 'Sujari',
     'lname': 'Britt',
     'cello_details': '',
     'bio': "Sujari Britt showed her prodigious talent and uncanny devotion to and understanding of music from a very early age.  She began formal study of the cello at age four, following her study on the violin, and piano. Sujari earned her Bachelor's of Music (2018) in Classical Cello Performance at Manhattan School of Music in the studio of distinguished pedagogue, author and cellist Marion Feldman. Sujari presently studies with renowned cellist and pedagogue Martti Rousi, Sibelius Academy in pursuit of her Master's of Classical Cello. In February 2019, Sujari is a featured artist at Musiikkotalo, Cellofest Opening Gala in Helisinki, Finland. Sujari also is featured at CUNY/Queens College, where she will present the Elgar, Cello Concerto in E minor.",
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615508899/seed_cellist_photos/sujari_rhrnmk.webp',
     'music_url': '',
     'teacher_ids': [24]
     },
    {'fname': 'Marion',
     'lname': 'Feldman',
     'cello_details': '',
     'bio': '',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615510910/seed_cellist_photos/feldman_ccdmzc.jpg',
     'music_url': '',
     'teacher_ids': [25, 10]
     },
    {'fname': 'Bernard',
     'lname': 'Greenhouse',
     'cello_details': '',
     'bio': '',
     'img_url': '',
     'music_url': '',
     'teacher_ids': []
     },
    {'fname': 'Shauna',
     'lname': 'Rolston',
     'cello_details': '',
     'bio': '',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615508898/seed_cellist_photos/shauna_rolston_rrmgwq.jpg',
     'music_url': '',
     'teacher_ids': [19]
     },
    {'fname': 'Bion',
     'lname': 'Tsang',
     'cello_details': '',
     'bio': '',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615508896/seed_cellist_photos/biontsang_riaute.png',
     'music_url': '',
     'teacher_ids': [19]
     },
    {'fname': 'Paul',
     'lname': 'Wiancko',
     'cello_details': '',
     'bio': '',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615508900/seed_cellist_photos/wiancko2_ljq5cz.jpg',
     'music_url': '',
     'teacher_ids': []
     },
    {'fname': 'Inbal',
     'lname': 'Segev',
     'cello_details': '',
     'bio': '',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615508897/seed_cellist_photos/InbalSegev-9GrantLegan-1365x2048_qdu1fu.jpg',
     'music_url': '',
     'teacher_ids': [14, 25, 30]
     },
    {'fname': 'Harvey',
     'lname': 'Shapiro',
     'cello_details': '',
     'bio': '',
     'img_url': '',
     'music_url': '',
     'teacher_ids': []
     },
    {'fname': 'David',
     'lname': 'Geringas',
     'cello_details': '',
     'bio': '',
     'img_url': '',
     'music_url': '',
     'teacher_ids': [32]
     },
    {'fname': 'Mstislav',
     'lname': 'Rostropovich',
     'cello_details': '',
     'bio': '',
     'img_url': '',
     'music_url': '',
     'teacher_ids': []
     },
    {'fname': 'Mischa',
     'lname': 'Maisky',
     'cello_details': '',
     'bio': '',
     'img_url': '',
     'music_url': '',
     'teacher_ids': [32]
     },
    {'fname': 'Natalia',
     'lname': 'Gutman',
     'cello_details': '',
     'bio': '',
     'img_url': '',
     'music_url': '',
     'teacher_ids': [32]
     },
    {'fname': 'Stephen',
     'lname': 'De\'ak',
     'cello_details': '',
     'bio': '',
     'img_url': '',
     'music_url': '',
     'teacher_ids': []
     },
    {'fname': 'Adolf',
     'lname': 'Schiffer',
     'cello_details': '',
     'bio': '',
     'img_url': '',
     'music_url': '',
     'teacher_ids': []
     },
    {'fname': 'Felix',
     'lname': 'Salmond',
     'cello_details': '',
     'bio': '',
     'img_url': '',
     'music_url': '',
     'teacher_ids': []
     },
    {'fname': 'Eleonore',
     'lname': 'Schoenfeld',
     'cello_details': '',
     'bio': '',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615508898/seed_cellist_photos/schoenfeld_jzu65l.jpg',
     'music_url': '',
     'teacher_ids': []
     },
    {'fname': 'Maximilian',
     'lname': 'Hornung',
     'cello_details': '',
     'bio': '',
     'img_url': '',
     'music_url': '',
     'teacher_ids': [31]
     },
    {'fname': 'Brian',
     'lname': 'Thornton',
     'cello_details': '',
     'bio': '',
     'img_url': 'https://visit.georgetown.org/wp-content/uploads/sites/45/2020/02/Brian-Thornton-cello-600x600.jpg',
     'music_url': '',
     'teacher_ids': [20]
     },
    {'fname': 'Lynn',
     'lname': 'Harrell',
     'cello_details': 'Harrell performed on a 1720 Montagnana cello and later a 1673 Stradivari that had once been owned by Jacqueline du Pré',
     'bio': '',
     'img_url': 'https://www.kusc.org/wp-content/uploads/2018/12/Lynn-Harrell-c-Christian-Steiner.jpg',
     'music_url': '',
     'teacher_ids': [20, 10]
     },
    {'fname': 'John',
     'lname': 'Sharp',
     'cello_details': '',
     'bio': '',
     'img_url': '',
     'music_url': '',
     'teacher_ids': [20]
     },
    {'fname': 'Mitch',
     'lname': 'Maxwell',
     'cello_details': '',
     'bio': '',
     'img_url': '',
     'music_url': '',
     'teacher_ids': [20]
     },
    {'fname': 'Christy',
     'lname': 'Curb',
     'cello_details': '',
     'bio': '',
     'img_url': '',
     'music_url': '',
     'teacher_ids': [20]
     },
    {'fname': 'Rachel',
     'lname': 'Bernstein',
     'cello_details': '',
     'bio': '',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615510910/seed_cellist_photos/rbernstein_kf9mg6.jpg',
     'music_url': '',
     'teacher_ids': [20]
     },
    {'fname': 'Eric',
     'lname': 'Tannenbaum',
     'cello_details': '',
     'bio': '',
     'img_url': '',
     'music_url': '',
     'teacher_ids': [3]
     },
    {'fname': 'Jonathan',
     'lname': 'Butler',
     'cello_details': '',
     'bio': '',
     'img_url': 'https://res.cloudinary.com/cellotree/image/upload/v1615510910/seed_cellist_photos/butler_qo07qh.jpg',
     'music_url': '',
     'teacher_ids': [2]
     },
    {'fname': 'Ron',
     'lname': 'Leonard',
     'cello_details': '',
     'bio': '',
     'img_url': '',
     'music_url': '',
     'teacher_ids': []
     },
]
